export const FETCH_TODOS = 'FETCH_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO_TITLE = 'UPDATE_TODO_TITLE';
export const UPDATE_TODO_CHECKBOX = 'UPDATE_TODO_CHECKBOX';
